"""add project_templates.downloads_count

Revision ID: 48b0a33cc53a
Revises: 9ad19d49fa72
Create Date: 2026-08-03 11:05:55.527518

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '48b0a33cc53a'
down_revision: str | None = '9ad19d49fa72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing kits with 0.
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('downloads_count', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_column('downloads_count')

    # ### end Alembic commands ###
