"""create prompts and prompt_versions

Revision ID: 58e8854653f8
Revises: f9bd49b1f10d
Create Date: 2026-07-15 15:04:29.895747

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '58e8854653f8'
down_revision: str | None = 'f9bd49b1f10d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.Enum('UI', 'BACKEND', 'DATABASE', 'API', 'ARCHITECTURE', 'SECURITY', 'OPTIMIZATION', 'TESTING', 'BUG_FIX', 'DEPLOYMENT', 'DOCUMENTATION', 'CODE_REVIEW', 'REFACTORING', 'OTHER', name='prompttype', native_enum=False, length=20), nullable=False),
    sa.Column('complexity', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='complexity', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='promptstatus', native_enum=False, length=20), nullable=False),
    sa.Column('framework', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.Column('ai_model', sa.String(length=60), nullable=True),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('copies_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('forked_from_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_prompts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forked_from_id'], ['prompts.id'], name=op.f('fk_prompts_forked_from_id_prompts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_ai_model'), ['ai_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_forked_from_id'), ['forked_from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_prompt_type'), ['prompt_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_title'), ['title'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_prompt_versions_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_versions_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('prompt_id', 'version_number', name='uq_prompt_version_number')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_id'), ['prompt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_author_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_title'))
        batch_op.drop_index(batch_op.f('ix_prompts_status'))
        batch_op.drop_index(batch_op.f('ix_prompts_slug'))
        batch_op.drop_index(batch_op.f('ix_prompts_prompt_type'))
        batch_op.drop_index(batch_op.f('ix_prompts_language'))
        batch_op.drop_index(batch_op.f('ix_prompts_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_framework'))
        batch_op.drop_index(batch_op.f('ix_prompts_forked_from_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_author_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_ai_model'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
