"""add collections, collection_items, likes, bookmarks

Revision ID: 5f76cf247a73
Revises: c1e5d4b8eb6b
Create Date: 2026-07-15 17:38:26.093876

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = '5f76cf247a73'
down_revision: str | None = 'c1e5d4b8eb6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_collections_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_slug'), ['slug'], unique=True)

    op.create_table('collection_items',
    sa.Column('collection_id', app.db.types.GUID(), nullable=False),
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_collection_items_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items')),
    sa.UniqueConstraint('collection_id', 'prompt_id', name='uq_collection_prompt')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('prompt_bookmarks',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_bookmarks_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prompt_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_bookmarks')),
    sa.UniqueConstraint('user_id', 'prompt_id', name='uq_bookmark_user_prompt')
    )
    with op.batch_alter_table('prompt_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_bookmarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_bookmarks_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('prompt_likes',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_likes_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prompt_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_likes')),
    sa.UniqueConstraint('user_id', 'prompt_id', name='uq_like_user_prompt')
    )
    with op.batch_alter_table('prompt_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_likes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_likes_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_likes_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_likes_id'))

    op.drop_table('prompt_likes')
    with op.batch_alter_table('prompt_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_bookmarks_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_bookmarks_id'))

    op.drop_table('prompt_bookmarks')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_collection_items_id'))
        batch_op.drop_index(batch_op.f('ix_collection_items_collection_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_slug'))
        batch_op.drop_index(batch_op.f('ix_collections_name'))
        batch_op.drop_index(batch_op.f('ix_collections_is_public'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))
        batch_op.drop_index(batch_op.f('ix_collections_author_id'))

    op.drop_table('collections')
    # ### end Alembic commands ###
