"""add prompts.allow_contributions

Revision ID: 7a094ad260f3
Revises: a2c90b0ccc52
Create Date: 2026-08-04 17:20:17.497382

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7a094ad260f3'
down_revision: str | None = 'a2c90b0ccc52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        # server_default so existing prompts stay closed to contributions.
        batch_op.add_column(
            sa.Column(
                'allow_contributions', sa.Boolean(), nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_column('allow_contributions')

    # ### end Alembic commands ###
