"""catch up: keys, teams, community, templates, ratings, embeddings

Revision ID: 9ad19d49fa72
Revises: 0dbcc18c04ad
Create Date: 2026-08-03 11:03:23.055621

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.db.types

revision: str = '9ad19d49fa72'
down_revision: str | None = '0dbcc18c04ad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_hashed_key'), ['hashed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_teams_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('project_templates',
    sa.Column('project_id', app.db.types.GUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('stack', sa.String(length=200), nullable=True),
    sa.Column('setup_command', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_templates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_templates')),
    sa.UniqueConstraint('project_id', name='uq_project_template')
    )
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_templates_project_id'), ['project_id'], unique=False)

    op.create_table('team_invites',
    sa.Column('team_id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_by', app.db.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_team_invites_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_invites_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invites'))
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_token'), ['token'], unique=True)

    op.create_table('team_members',
    sa.Column('team_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('template_previews',
    sa.Column('project_id', app.db.types.GUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_template_previews_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_previews'))
    )
    with op.batch_alter_table('template_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_previews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_previews_project_id'), ['project_id'], unique=False)

    op.create_table('prompt_comments',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_prompt_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_comments_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_comments'))
    )
    with op.batch_alter_table('prompt_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_comments_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('prompt_embeddings',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_embeddings_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_embeddings')),
    sa.UniqueConstraint('prompt_id', name='uq_embedding_prompt')
    )
    with op.batch_alter_table('prompt_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_embeddings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_embeddings_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('prompt_ratings',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_ratings_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prompt_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_ratings')),
    sa.UniqueConstraint('user_id', 'prompt_id', name='uq_rating_user_prompt')
    )
    with op.batch_alter_table('prompt_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_ratings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_ratings_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('prompt_reports',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('reporter_id', app.db.types.GUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_reports_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_prompt_reports_reporter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_reports'))
    )
    with op.batch_alter_table('prompt_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_reports_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_reports_status'), ['status'], unique=False)

    op.create_table('prompt_teams',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('team_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_teams_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_prompt_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_teams')),
    sa.UniqueConstraint('prompt_id', name='uq_prompt_team')
    )
    with op.batch_alter_table('prompt_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_teams_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_teams_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('prompt_assets', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)

    # server_default backfills existing rows; without it a NOT NULL add fails
    # on any table that already has data.
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('rating_avg', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('rating_count', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_avg')

    with op.batch_alter_table('prompt_assets', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('prompt_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_teams_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_teams_id'))

    op.drop_table('prompt_teams')
    with op.batch_alter_table('prompt_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_reports_status'))
        batch_op.drop_index(batch_op.f('ix_prompt_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_reports_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_reports_id'))

    op.drop_table('prompt_reports')
    with op.batch_alter_table('prompt_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_ratings_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_ratings_id'))

    op.drop_table('prompt_ratings')
    with op.batch_alter_table('prompt_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_embeddings_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_embeddings_id'))

    op.drop_table('prompt_embeddings')
    with op.batch_alter_table('prompt_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_comments_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_comments_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_comments_author_id'))

    op.drop_table('prompt_comments')
    with op.batch_alter_table('template_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_previews_project_id'))
        batch_op.drop_index(batch_op.f('ix_template_previews_id'))

    op.drop_table('template_previews')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_token'))
        batch_op.drop_index(batch_op.f('ix_team_invites_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invites_id'))
        batch_op.drop_index(batch_op.f('ix_team_invites_email'))

    op.drop_table('team_invites')
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_templates_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_templates_id'))
        batch_op.drop_index(batch_op.f('ix_project_templates_category'))

    op.drop_table('project_templates')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_owner_id'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_hashed_key'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
