"""add auth_tokens for email verification and password reset

Revision ID: a2c90b0ccc52
Revises: 48b0a33cc53a
Create Date: 2026-08-03 11:15:11.513697

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.db.types

revision: str = 'a2c90b0ccc52'
down_revision: str | None = '48b0a33cc53a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFY', 'PASSWORD_RESET', name='tokenpurpose', native_enum=False, length=20), nullable=False),
    sa.Column('hashed_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens'))
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_hashed_token'), ['hashed_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_hashed_token'))

    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
