"""add prompt_assets

Revision ID: bac925ac0ef5
Revises: 9a7bd900a094
Create Date: 2026-07-15 15:41:29.423729

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = 'bac925ac0ef5'
down_revision: str | None = '9a7bd900a094'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_assets',
    sa.Column('prompt_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.Enum('SCREENSHOT', 'IMAGE', 'VIDEO', 'LIVE_DEMO', 'GENERATED_HTML', 'GENERATED_CODE', name='assetkind', native_enum=False, length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_assets_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_assets'))
    )
    with op.batch_alter_table('prompt_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_assets_prompt_id'), ['prompt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_assets_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_assets_id'))

    op.drop_table('prompt_assets')
    # ### end Alembic commands ###
