"""add projects, modules, components and prompt.component_id

Revision ID: c1e5d4b8eb6b
Revises: bac925ac0ef5
Create Date: 2026-07-15 15:58:53.509789

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

revision: str = 'c1e5d4b8eb6b'
down_revision: str | None = 'bac925ac0ef5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_projects_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('modules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('project_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_modules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules'))
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_slug'), ['slug'], unique=True)

    op.create_table('components',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('module_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_components_module_id_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components'))
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_slug'), ['slug'], unique=True)

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', app.db.types.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prompts_component_id'), ['component_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_prompts_component_id_components'), 'components', ['component_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prompts_component_id_components'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prompts_component_id'))
        batch_op.drop_column('component_id')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_slug'))
        batch_op.drop_index(batch_op.f('ix_components_module_id'))
        batch_op.drop_index(batch_op.f('ix_components_id'))

    op.drop_table('components')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_slug'))
        batch_op.drop_index(batch_op.f('ix_modules_project_id'))
        batch_op.drop_index(batch_op.f('ix_modules_id'))

    op.drop_table('modules')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_author_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
